import Head from "next/head";
import { api } from "@/utils/api";
import { randomUUID } from "crypto";

export default function Home() {
  const { data } = api.target.getData.useQuery(undefined, {
    staleTime: 1,
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="bg-amber-600 py-2 text-center text-white">Testing</h1>
      <div className="flex flex-1 flex-col">
        {data?.map((d, i) => (
          <pre
            key={`${i}-${d.id}-${Math.floor(Math.random() * 9999)}`}
            className={`${
              i % 2 === 0 ? "bg-stone-700" : "bg-stone-500"
            } p-4 text-white`}
          >
            {d.json?.toString()}
          </pre>
        ))}
      </div>
    </>
  );
}
